---
# tasks file for roles/ubuntu/common
- name: ensure aptitude is installed
  apt:
    pkg: aptitude
    state: latest

- name: Ensure packet manager is up to date
  apt:
    update_cache: yes

- name: Ensure installed packets are up to date
  apt:
    upgrade: full

- name: ensure common packages are installed
  apt:
    pkg:
      - zsh
      - git-core
    state: latest

- name: ensure oh-my-zsh is installed
  get_url:
    url: https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh
    dest: /opt/install.sh
    mode: '0744'
  notify:
    - install oh-my-zsh
    - change root shell