application_name      = "thyart-web"
backend_name          = "thyart-api"
team_name             = "ThyArt"
version               = "0.0.1"
aws_region            = "eu-west-1"
codebuild_image_name  = "kkarczmarczyk/node-yarn:latest"