all:
  children:

    backend:
      hosts:
        thyart.staging.backend:
          ansible_ssh_host: staging.api.thyart.fr
          ansible_user: root

        thyart.production.backend:
          ansible_ssh_host: api.thyart.fr
          ansible_user: root

    frontend:
      hosts:
        thyart.staging.frontend:
          ansible_ssh_host: staging.thyart.fr
          ansible_user: root

        thyart.production.frontend:
          ansible_ssh_host: www.thyart.fr
          ansible_user: root

    mariadb:
      hosts:
        thyart.staging.mariadb:
          ansible_ssh_host: staging.db.thyart.fr
          ansible_user: root

        thyart.production.mariadb:
          ansible_ssh_host: db.thyart.fr
          ansible_user: root