###

- name: common
  hosts:
    - all
  roles:
    - debian/common

- name: mariadb
  hosts:
    - mariadb
  roles:
    - debian/mariadb

- name: backend
  hosts:
    - backend
  roles:
    - debian/php
    - debian/nginx
    - debian/environment

- name: frontend
  hosts:
    - frontend
  roles:
    - debian/nginx
    - debian/environment