###

- name: common
  hosts:
    - all
  roles:
    - debian/common

- name: mariadb
  hosts:
    - mariadb
  roles:
    - debian/mariadb

- name: backend
  hosts:
    - backend
  roles:
    - debian/php
    - debian/nginx
    - debian/environment

- name: frontend
  hosts:
    - frontend
  roles:
    - debian/nginx
    - debian/environment

- name: documentation
  hosts:
    - documentation
  roles:
    - debian/nginx

- name: datadog
  hosts:
    - servers
  roles:
    - { role: Datadog.datadog, become: yes, datadog_api_key: "8a31dffb6b1b2d0a192a847aceab6172" }