---
# tasks file for roles/debian/environment
- name: generate environment variable file
  template:
    src: "{{ environment_file_template }}"
    dest: /etc/environment
  when: environment_file_template is defined

- include: configuration.yml
  when: configuration_environment is defined and dotenv_file_template is defined