---
# tasks file for roles/debian/php

- name: install mandatory packages
  apt:
    pkg:
      - ca-certificates
      - apt-transport-https

- name: add php version apt-key
  apt_key:
    url: https://packages.sury.org/php/apt.gpg

- name: add php repository
  apt_repository:
    repo: 'deb https://packages.sury.org/php/ stretch main'
    state: present
    update_cache: yes

- name: install php
  apt:
    pkg:
      - php{{ php_version }}
      - php{{ php_version }}-fpm
      - php{{ php_version }}-cli
      - php{{ php_version }}-common
      - php{{ php_version }}-opcache
      - php{{ php_version }}-curl
      - php{{ php_version }}-mbstring
      - php{{ php_version }}-mysql
      - php{{ php_version }}-zip
      - php{{ php_version }}-xml
      - php{{ php_version }}-gd
      - composer